HelpDeskSoftware/Models/Ticket.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using HelpDeskSoftware.Controllers;

namespace HelpDeskSoftware.Models
{
    public class Ticket
    {
        public int TicketId { get; set; }

        public string Description { get; set; }

        public DateTime TimeOfEntry { get; set; }

        public DateTime Deadline { get; set; }

        public Ticket(int id, string ticket, string deadline, DateTime entrytime)
        {
            TicketId = id;
            Description = ticket;
            TimeOfEntry = entrytime;

            DateTime correctDeadline = DateTime.Parse(deadline);
                        
            if (correctDeadline.Date == TimeOfEntry.Date
                && correctDeadline.TimeOfDay <= TimeOfEntry.TimeOfDay)
            {
                Deadline = correctDeadline.AddDays(1);
            }
            else
            {
                Deadline = correctDeadline;
            }            
        }
    }
}

HelpDeskSoftware/Controllers/TicketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HelpDeskSoftware.Models;
using HelpDeskSoftware.Services;

namespace HelpDeskSoftware.Controllers
{
    public class TicketsController : Controller
    {
        public ActionResult Index(int? ticketId)
        {
            TicketRepository.CreateTickets();

            if (ticketId != null)
            {
                var doneTicket = Tickets.Find(x => x.TicketId == ticketId);
                Tickets.Remove(doneTicket);
            }

            return View(Tickets.OrderByDescending(x => x.Deadline).ToList());
        }

        public static readonly List<Ticket> Tickets = new List<Ticket>();

        [HttpPost]
        public ActionResult Add(string ticket, string deadline)
        {
            DateTime entryTime = DateTime.Now;
            int ticketId;

            if (!Tickets.Any())
            {
                ticketId = 1;
            }
            else if (Tickets.Find(x => x.Description == ticket) != null)
            {
                TempData["DuplicateItem"] = "Inserted ticket is already on the list.";
                return RedirectToAction("Index");
            }
            else
            {
                ticketId = (Tickets.Last()).TicketId + 1;
            }

            if (!DateTime.TryParse(deadline, out DateTime validDeadline))
            {
                TempData["WrongInputError"] = "Please insert correct date/time.";
                return RedirectToAction("Index");
            }
            else if (validDeadline.Date < DateTime.Now.Date)
            {
                TempData["WrongDateError"] = "Please insert correct date";
                return RedirectToAction("Index");
            }

            var newTicket = new Ticket(ticketId, ticket, validDeadline.ToString(), entryTime);
            Tickets.Add(newTicket);

            return RedirectToAction("Index");
        }
    }
}

HelpDeskSoftware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Task notification system</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Task notification system", "Index", "Tickets", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Tickets", "Index", "Tickets")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

HelpDeskSoftware/Views/Tickets/Index.cshtml
@model List<HelpDeskSoftware.Models.Ticket>

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">

    <p>Add a ticket:</p>

    <form action="@Url.Action("Add")" method="Post">
        <input type="text" class="input-group-lg col-xs-12" name="ticket" autofocus required />
        <br />
        <text class="text-warning"> @TempData["DuplicateItem"] </text>
        <p>
            Deadline:<br />
            <input type="text" class="input-sm" name="deadline" placeholder="2019.03.16 16:00" required />
            <text class="text-warning">
                @TempData["WrongInputError"]
                @TempData["WrongDateError"]
            </text>

        </p>

        <input type="submit" value="Submit" />
    </form>


</div>
@*<input type="button" value="Add tickets to list for testing" onclick="@HelpDeskSoftware.Controllers.TicketsController.Tickets" />*@


<table class="table">
    <tr>
        <th>Id</th>
        <th>Time of Entry</th>
        <th>Description</th>
        <th>Deadline</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.TicketId</td>
            <td>
                @item.TimeOfEntry.ToShortDateString(),
                @item.TimeOfEntry.ToShortTimeString()
            </td>
            <td>
                @item.Description
            </td>

            @if ((item.Deadline.Date == DateTime.Now.Date
                    && item.Deadline.Hour < DateTime.Now.Hour)
                || item.Deadline.Date < DateTime.Now.Date
                || (item.Deadline.Date == DateTime.Now.Date
                    && (DateTime.Now > item.Deadline ? (DateTime.Now - item.Deadline) : (item.Deadline - DateTime.Now))
                        .TotalMinutes <= 60))
            {
                <td class="text-warning">
                    @item.Deadline.ToShortDateString()
                    <text>, by</text>
                    @item.Deadline.ToShortTimeString()
                </td>
            }
            else
            {
                <td>
                    @item.Deadline.ToShortDateString()
                    <text>, by</text>
                    @item.Deadline.ToShortTimeString()
                </td>
            }

            <td>
                <input type="button" onclick="location.href = '@Url.Action("Index", new { ticketId = @item.TicketId })'"
                       value="Ticket resolved (remove)" />
            </td>
        </tr>
    }
</table>